### ISSUE TITLE
Implement ridecounter boards

### ISSUE THREAD

**Issue by JVerbruggen** [JVerbruggen/jrides#2]
User stories
- Administrator should be able to get a ridecounters map with /jrides ridecounteroverview <coaster> <board_name>
- Configurator should be able to configure ride counter map background in `<coaster>/<coaster>.coaster.yml`, ie:
```yml
config:
  rideCounterBoards:
    board_1:
      type: top # top, daily (, weekly)
      lines: [10, 20, 30] # each entry is the amount of pixels from the top, amount of entries is equal to how many records should be displayed (3 items = top 3), Also, if entry exceeds pixel count of map 1's height, a second map should also be created (for multi map ride counter boards)
      mapIds: [1561, 1562] # Amount should be the same as are created by lines attribute, used for packets
      lineFormat: %RANK%: %PLAYER_NAME%
```
- Default ridecounter board background is at location `jrides/default_ridecounterboard.png`
- Ridecounter board background is at location `jrides/coasters/<coaster>/assets/ridecounterboards/board_1.png` (file name same as board name)
- When a ridecounter updates, a ridecounterupdateevent should be dispatched (dunno if it already happens). A listener should listen for the event and update the map. (so no direct relation!!!!) EVENT SOURCING
-
